// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: messageSearch.proto

package messageSearch

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for SearchMessageService services

func NewSearchMessageServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for SearchMessageService services

type SearchMessageService interface {
	//搜索消息
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
}

type searchMessageService struct {
	c    client.Client
	name string
}

func NewSearchMessageService(name string, c client.Client) SearchMessageService {
	return &searchMessageService{
		c:    c,
		name: name,
	}
}

func (c *searchMessageService) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.name, "SearchMessageService.search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SearchMessageService services

type SearchMessageServiceHandler interface {
	//搜索消息
	Search(context.Context, *SearchRequest, *SearchResponse) error
}

func RegisterSearchMessageServiceHandler(s server.Server, hdlr SearchMessageServiceHandler, opts ...server.HandlerOption) error {
	type searchMessageService interface {
		Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error
	}
	type SearchMessageService struct {
		searchMessageService
	}
	h := &searchMessageServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&SearchMessageService{h}, opts...))
}

type searchMessageServiceHandler struct {
	SearchMessageServiceHandler
}

func (h *searchMessageServiceHandler) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.SearchMessageServiceHandler.Search(ctx, in, out)
}
