// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: userGroupMembers.proto

package userGroupMembers

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UserGroupMembersService service

func NewUserGroupMembersServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for UserGroupMembersService service

type UserGroupMembersService interface {
	//添加群成员
	AddMember(ctx context.Context, in *AddMemberRequest, opts ...client.CallOption) (*AddMemberResponse, error)
	//删除群成员
	DelByMemberId(ctx context.Context, in *DelByMemberIdRequest, opts ...client.CallOption) (*DelByMemberIdResponse, error)
	//解散群
	DelMembers(ctx context.Context, in *DelMembersRequest, opts ...client.CallOption) (*DelMembersResponse, error)
	//获取群列表
	MemberGroups(ctx context.Context, in *MemberGroupsRequest, opts ...client.CallOption) (*MemberGroupsResponse, error)
	//获取群成员列表
	Members(ctx context.Context, in *MembersRequest, opts ...client.CallOption) (*MembersResponse, error)
}

type userGroupMembersService struct {
	c    client.Client
	name string
}

func NewUserGroupMembersService(name string, c client.Client) UserGroupMembersService {
	return &userGroupMembersService{
		c:    c,
		name: name,
	}
}

func (c *userGroupMembersService) AddMember(ctx context.Context, in *AddMemberRequest, opts ...client.CallOption) (*AddMemberResponse, error) {
	req := c.c.NewRequest(c.name, "UserGroupMembersService.AddMember", in)
	out := new(AddMemberResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGroupMembersService) DelByMemberId(ctx context.Context, in *DelByMemberIdRequest, opts ...client.CallOption) (*DelByMemberIdResponse, error) {
	req := c.c.NewRequest(c.name, "UserGroupMembersService.DelByMemberId", in)
	out := new(DelByMemberIdResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGroupMembersService) DelMembers(ctx context.Context, in *DelMembersRequest, opts ...client.CallOption) (*DelMembersResponse, error) {
	req := c.c.NewRequest(c.name, "UserGroupMembersService.DelMembers", in)
	out := new(DelMembersResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGroupMembersService) MemberGroups(ctx context.Context, in *MemberGroupsRequest, opts ...client.CallOption) (*MemberGroupsResponse, error) {
	req := c.c.NewRequest(c.name, "UserGroupMembersService.MemberGroups", in)
	out := new(MemberGroupsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGroupMembersService) Members(ctx context.Context, in *MembersRequest, opts ...client.CallOption) (*MembersResponse, error) {
	req := c.c.NewRequest(c.name, "UserGroupMembersService.Members", in)
	out := new(MembersResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserGroupMembersService service

type UserGroupMembersServiceHandler interface {
	//添加群成员
	AddMember(context.Context, *AddMemberRequest, *AddMemberResponse) error
	//删除群成员
	DelByMemberId(context.Context, *DelByMemberIdRequest, *DelByMemberIdResponse) error
	//解散群
	DelMembers(context.Context, *DelMembersRequest, *DelMembersResponse) error
	//获取群列表
	MemberGroups(context.Context, *MemberGroupsRequest, *MemberGroupsResponse) error
	//获取群成员列表
	Members(context.Context, *MembersRequest, *MembersResponse) error
}

func RegisterUserGroupMembersServiceHandler(s server.Server, hdlr UserGroupMembersServiceHandler, opts ...server.HandlerOption) error {
	type userGroupMembersService interface {
		AddMember(ctx context.Context, in *AddMemberRequest, out *AddMemberResponse) error
		DelByMemberId(ctx context.Context, in *DelByMemberIdRequest, out *DelByMemberIdResponse) error
		DelMembers(ctx context.Context, in *DelMembersRequest, out *DelMembersResponse) error
		MemberGroups(ctx context.Context, in *MemberGroupsRequest, out *MemberGroupsResponse) error
		Members(ctx context.Context, in *MembersRequest, out *MembersResponse) error
	}
	type UserGroupMembersService struct {
		userGroupMembersService
	}
	h := &userGroupMembersServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserGroupMembersService{h}, opts...))
}

type userGroupMembersServiceHandler struct {
	UserGroupMembersServiceHandler
}

func (h *userGroupMembersServiceHandler) AddMember(ctx context.Context, in *AddMemberRequest, out *AddMemberResponse) error {
	return h.UserGroupMembersServiceHandler.AddMember(ctx, in, out)
}

func (h *userGroupMembersServiceHandler) DelByMemberId(ctx context.Context, in *DelByMemberIdRequest, out *DelByMemberIdResponse) error {
	return h.UserGroupMembersServiceHandler.DelByMemberId(ctx, in, out)
}

func (h *userGroupMembersServiceHandler) DelMembers(ctx context.Context, in *DelMembersRequest, out *DelMembersResponse) error {
	return h.UserGroupMembersServiceHandler.DelMembers(ctx, in, out)
}

func (h *userGroupMembersServiceHandler) MemberGroups(ctx context.Context, in *MemberGroupsRequest, out *MemberGroupsResponse) error {
	return h.UserGroupMembersServiceHandler.MemberGroups(ctx, in, out)
}

func (h *userGroupMembersServiceHandler) Members(ctx context.Context, in *MembersRequest, out *MembersResponse) error {
	return h.UserGroupMembersServiceHandler.Members(ctx, in, out)
}
